Some fixes

diff --git a/savestate b/savestate
--- a/savestate
+++ b/savestate
@@ -2,15 +2,17 @@
 image="$1"
 
 mkfifo fifo # &> /dev/null
-[[ -r fifo && -w fifo && -p fifo ]] || { echo "fifo fail"; exit 1; }
+[[ -r fifo && -w fifo && -p fifo ]] || {
+	echo "fifo fail"
+	exit 1
+}
 
-< fifo qemu-system-x86_64 -kernel shbot-kernel -initrd shbot.cpio.gz -hda "$image" -net none -m 72 -nographic -append irc |
-    while read -r f
-    do
-        printf '%s\n' "$f" >&2
-        if [[ $f = $'Ready\r' ]]; then
-            printf '\x01c\nsavevm\nquit\n'
-        fi
-    done > fifo
+qemu-system-x86_64 <fifo -kernel shbot-kernel -initrd shbot.cpio.gz -hda "$image" -net none -m 72 -nographic -append irc |
+	while read -r f; do
+		printf '%s\n' "$f" >&2
+		if [[ $f =~ ^.*'Ready'.*$ ]]; then
+			printf '\x01c\nsavevm 1\nquit\n'
+		fi
+	done >fifo
 
 rm -f fifo
